name: flutter_detector
description: Flutter application with possible way of TFLite models usage on heavy camera streams

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  provider: ^4.3.2+1
  tflite: ^1.1.1
  camera: ^0.5.8+5
#  firebase_ml_vision: ^0.9.10
#  firebase_core: ^1.21.1
#  get: ^4.3.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_name: ^0.0.1

flutter_launcher_name:
  name: "Emotion Recognition"

flutter:

  uses-material-design: true

  assets:
    - assets/